### PR TITLE
update to Cesium 1.45

### LINKED ISSUE #2: package.json has invalid name
"Cesium + Three JS Experiment" should be changed to something like "cesium-threejs-experiment".

### LINKED ISSUE #5: Globe is not visible
I don't see a globe in the live demo:

screen shot 2018-05-30 at 12 26 47 am

### PR DESCRIPTION
**Pull request by likangning93**
Fixes https://github.com/AnalyticalGraphicsInc/cesium-threejs-experiment/issues/2
Will fix https://github.com/AnalyticalGraphicsInc/cesium-threejs-experiment/issues/5 when we re-push to the github pages branch.

### CODE REVIEW

**Comment by lilleyse** [comment]
The package name needs to be all lowercase ([source](https://www.npmjs.com/package/validate-npm-package-name)): `cesium-threejs-experiment`

Were there any issues related to log depth?

We should use caret versions in the `package.json` so we don't have to update manually: e.g. `"cesium": "^1.45.0"`

**Comment by likangning93** [comment]
> Were there any issues related to log depth?

None since it's two separate contexts. The Three.js scene has some z-fighting like before though, maybe we can look into activating log depth there in the future when we update the Three.js version.

**Comment by lilleyse** [comment]
Oh that's true. Thanks!

**Comment by lilleyse** [comment]
I don't have merge access here - @likangning93 can you merge?

**Pull request merged**
